[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
runner = "qemu-system-arm -cpu cortex-m4 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -s -kernel"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]
